### ISSUE TITLE
Use raw_input for username

### ISSUE THREAD

**Issue by casdr** [RobotKernel/artstation-scrape-likes#1]
`input()` allows any type of input, including variables. Use `raw_input()` to make sure everything you type is converted to a string.

**Comment by RobotKernel** [comment]
that would be the case in python 2, i expect. As this is written in python 3 `raw_input()` has been replaced with `input()` to get the old behaviour you would need to use `eval(input())`. see: https://docs.python.org/3/whatsnew/3.0.html

**Comment by casdr** [comment]
Oh wait, I still was a bit sleepy :)
